services:
    backend:
        build: .
        ports:
            - "${PORT:-3000}:3000"
        environment:
            PORT: 3000
            MONGODB_URI: mongodb://root:secret@mongodb:27017/
            DATABASE_NAME: jsramverk
        depends_on:
            - mongodb
        restart: unless-stopped

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - mongodbdata:/data/db

volumes:
    mongodbdata:
