services:
    backend:
        build: .
        ports:
          - "${PORT:-3000}:3000"
        env_file:
          - .env
        environment:
          - MONGODB_URI=${MONGODB_URI}
          - PORT=3000
        restart: always

    # mongodb:
    #     image: mongo:latest
    #     container_name: mongodb
    #     ports:
    #         - "27017:27017"
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: root
    #         MONGO_INITDB_ROOT_PASSWORD: secret
    #     volumes:
    #         - mongodb_data:/data/db
    #     restart: always

# volumes:
#     mongodb_data:
